version: '3.8'
services:
  elastic:
    container_name: elastic
    image: elasticsearch:7.4.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"

  kibana:
    container_name: kibana
    image: kibana:7.4.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
