version: '3.7'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5.5
    ports:
      - "2181:2181"
    restart: on-failure

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=192.168.1.13
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - "KAFKA_CREATE_TOPICS=topicone:16:1"
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=0
    restart: on-failure

