version: '3.7'
services:
  docker-zookeeper:
    container_name: docker-zookeeper
    image: zookeeper:3.5.5
    ports:
      - "2181:2181"
    restart: on-failure

  docker-kafka:
    container_name: docker-kafka
    image: wurstmeister/kafka:2.12-2.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: docker-kafka
      KAFKA_ADVERTISED_PORTL: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: topicone:16:1,topictwo:16:1
      KAFKA_ZOOKEEPER_CONNECT: docker-zookeeper:2181
      KAFKA_BROKER_ID: 0
    restart: on-failure
