#!/usr/bin/env bash

dcmp="docker-compose "
for f in "$@"
do
  dcmp+="-f $f "
done

echo ""
echo ">"
echo "> Executing: $dcmp down --volumes"
echo "> "
echo ""
${dcmp} down --volumes || true

echo ""
echo ">"
echo "> Executing: $dcmp up --build --force-recreate"
echo ">"
echo ""
${dcmp} up --build --force-recreate
