version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secure
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    #  PGDATA: /var/lib/postgresql/data/pgdata
    #volumes:
    #  - "$HOME/pgdata:/var/lib/postgresql/data/pgdata"
