version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secure
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    #  - PGDATA=/var/lib/postgresql/data/pgdata
    #volumes:
    #  - "$HOME/pgdata:/var/lib/postgresql/data/pgdata"