version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo:4.2-bionic
    ports:
      - "9898:27017"
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "9696:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: password
